### ISSUE TITLE
Sys.executable sometimes gives wrong directory

### ISSUE THREAD

**Issue by Evernow** [Evernow/AutoDDU_CLI#6]
Saw an instance in the NVIDIA server ( https://discord.com/channels/185647255028629505/185808757115191296/952815438675468288 ) where somehow copying the sys.executable failed, having to fall back to the except method of downloading executable from github.

```
UTC 13/03/2022 19:01:03 Falled back to downloading from github method for going to Appdata directory due to error: Traceback (most recent call last):
  File "AutoDDU_CLI.py", line 366, in makepersist
  File "shutil.py", line 254, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jason\\Downloads\\AutoDDU_CLI.exe'
```

Same issue for user folder.

Interestingly the user did AutoDDU a day later and it finished fine:

```
UTC 14/03/2022 05:58:40 Successfully copied executable to new user
UTC 14/03/2022 05:58:40 Successfully copied executable to Appdata directory
```

There were no executable changes between these two runs, which has resulted in me being dumbfounded.

**Comment by Evernow** [comment]
Happened again: https://discord.com/channels/185647255028629505/185808757115191296/957087190918266890

**Comment by Evernow** [comment]
This was fixed a long time ago, cause was a misstype in os.path.join
